name: measure
channels:
  - conda-forge
dependencies:
  - alabaster=0.7.12=py_0
  - anyio=3.5.0=py310hbe9552e_0
  - appnope=0.1.2=py310hbe9552e_2
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310he2143c4_1
  - astroid=2.9.3=py310hbe9552e_0
  - asttokens=2.0.5=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - babel=2.9.1=pyh44b312d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.10.0=pyha770c72_0
  - black=22.1.0=pyhd8ed1ab_0
  - bleach=4.1.0=pyhd8ed1ab_0
  - blosc=1.21.0=h9f76cd9_0
  - boost-cpp=1.74.0=h128b0ad_5
  - branca=0.4.2=pyhd8ed1ab_0
  - brotli=1.0.9=h3422bc3_6
  - brotli-bin=1.0.9=h3422bc3_6
  - brotlipy=0.7.0=py310he2143c4_1003
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.18.1=h3422bc3_0
  - ca-certificates=2021.10.8=h4653dfc_0
  - cairo=1.16.0=hb99c34e_1009
  - certifi=2021.10.8=py310hbe9552e_1
  - cffi=1.15.0=py310hf10583b_0
  - cfitsio=4.0.0=h99351b2_0
  - charset-normalizer=2.0.10=pyhd8ed1ab_0
  - click=8.0.3=py310hbe9552e_1
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - coverage=6.3=py310he2143c4_0
  - cryptography=36.0.1=py310heb878e4_0
  - curl=7.81.0=h8fe1914_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.5.1=py310h1b49c16_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docutils=0.15.2=py310hbe9552e_3
  - entrypoints=0.3=pyhd8ed1ab_1003
  - execnet=1.9.0=pyhd8ed1ab_0
  - executing=0.8.2=pyhd8ed1ab_0
  - expat=2.4.3=hbdafb3b_0
  - fiona=1.8.20=py310h0fdc872_4
  - flake8=3.8.4=py_0
  - flit-core=3.6.0=pyhd8ed1ab_0
  - folium=0.12.1.post1=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.94=heb65262_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.29.0=py310he2143c4_0
  - freetype=2.10.4=h17b34a0_1
  - freexl=1.0.6=h27ca646_0
  - furo=2021.10.9=pyhd8ed1ab_0
  - geopandas=0.10.2=pyhd8ed1ab_1
  - geopandas-base=0.10.2=pyha770c72_1
  - geos=3.10.2=hbdafb3b_0
  - geotiff=1.7.0=h0dc1598_6
  - gettext=0.19.8.1=h049c9fb_1008
  - giflib=5.2.1=h27ca646_2
  - hdf4=4.2.15=h0ef36ac_3
  - hdf5=1.12.1=nompi_had0e5e0_103
  - icu=69.1=hbdafb3b_0
  - idna=3.3=pyhd8ed1ab_0
  - imagesize=1.3.0=pyhd8ed1ab_0
  - importlib-metadata=4.10.1=py310hbe9552e_0
  - importlib_resources=5.4.0=pyhd8ed1ab_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - invoke=1.6.0=pyhd8ed1ab_0
  - ipykernel=6.8.0=py310hc469350_0
  - ipython=8.0.1=py310hbe9552e_0
  - ipython_genutils=0.2.0=py_1
  - isort=5.10.1=pyhd8ed1ab_0
  - jbig=2.1=h3422bc3_2003
  - jedi=0.18.1=py310hbe9552e_0
  - jinja2=3.0.3=pyhd8ed1ab_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h3422bc3_0
  - json-c=0.15=hc6a1b29_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.4.0=pyhd8ed1ab_0
  - jupyter_client=7.1.2=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py310hbe9552e_1
  - jupyter_server=1.13.4=pyhd8ed1ab_0
  - jupyterlab=3.2.8=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.10.3=pyhd8ed1ab_0
  - kealib=1.4.14=h8a8d77f_3
  - kiwisolver=1.3.2=py310hd99b56e_1
  - krb5=1.19.2=hd92b7a7_3
  - lazy-object-proxy=1.7.1=py310he2143c4_0
  - lcms2=2.12=had6a04f_0
  - lerc=3.0=hbdafb3b_0
  - libblas=3.9.0=13_osxarm64_openblas
  - libbrotlicommon=1.0.9=h3422bc3_6
  - libbrotlidec=1.0.9=h3422bc3_6
  - libbrotlienc=1.0.9=h3422bc3_6
  - libcblas=3.9.0=13_osxarm64_openblas
  - libcurl=7.81.0=h8fe1914_0
  - libcxx=12.0.1=h168391b_1
  - libdap4=3.20.6=h8510809_2
  - libdeflate=1.8=h3422bc3_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libffi=3.4.2=h3422bc3_5
  - libgdal=3.4.1=h4176159_2
  - libgfortran=5.0.0.dev0=11_0_1_hf114ba7_23
  - libgfortran5=11.0.1.dev0=hf114ba7_23
  - libglib=2.70.2=h67e64d8_1
  - libiconv=1.16=h642e427_0
  - libkml=1.3.0=h893ab4d_1014
  - liblapack=3.9.0=13_osxarm64_openblas
  - libnetcdf=4.8.1=nompi_h96a3436_101
  - libnghttp2=1.46.0=he4cd7f6_0
  - libopenblas=0.3.18=openmp_h5dd58f0_0
  - libpng=1.6.37=hf7e6567_2
  - libpq=14.1=h8bb6238_1
  - librttopo=1.1.0=h56e3e6d_9
  - libsodium=1.0.18=h27ca646_1
  - libspatialindex=1.9.3=hbdafb3b_4
  - libspatialite=5.0.1=hde20a99_14
  - libssh2=1.10.0=hb80f160_2
  - libtiff=4.3.0=h74060c4_2
  - libwebp-base=1.2.2=h3422bc3_1
  - libxml2=2.9.12=hedbfbf4_1
  - libzip=1.8.0=h3887732_1
  - libzlib=1.2.11=hee7b306_1013
  - livereload=2.6.3=pyh9f0ad1d_0
  - llvm-openmp=12.0.1=hf3c4609_1
  - lz4-c=1.9.3=hbdafb3b_1
  - mapclassify=2.4.3=pyhd8ed1ab_0
  - markdown-it-py=2.0.1=pyhd8ed1ab_0
  - markupsafe=2.0.1=py310he2143c4_1
  - matplotlib-base=3.5.1=py310hacb9267_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mccabe=0.6.1=py_1
  - mdit-py-plugins=0.3.0=pyhd8ed1ab_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mistune=0.8.4=py310he2143c4_1005
  - munch=2.5.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=0.4.3=py310hbe9552e_4
  - myst-parser=0.16.1=pyhd8ed1ab_0
  - nbclassic=0.3.5=pyhd8ed1ab_0
  - nbclient=0.5.10=pyhd8ed1ab_1
  - nbconvert=6.4.1=py310hbe9552e_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.3=hc470f4d_0
  - nest-asyncio=1.5.4=pyhd8ed1ab_0
  - networkx=2.6.3=pyhd8ed1ab_1
  - notebook=6.4.8=pyha770c72_0
  - nspr=4.32=hbdafb3b_1
  - nss=3.74=h353d031_0
  - numpy=1.22.1=py310h567df17_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=h062765e_1
  - openssl=1.1.1l=h3422bc3_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.0=py310hdead3df_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.9.0=pyhd8ed1ab_0
  - pcre=8.45=hbdafb3b_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.4.0=py310h225ac4f_0
  - pip=21.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=h27ca646_0
  - platformdirs=2.3.0=pyhd8ed1ab_0
  - pluggy=1.0.0=py310hbe9552e_2
  - poppler=21.11.0=hb0dbcdf_0
  - poppler-data=0.4.11=hd8ed1ab_0
  - postgresql=14.1=h8fdef8c_1
  - proj=8.2.1=h2d984c1_0
  - prometheus_client=0.13.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.26=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py=1.11.0=pyh6c4a22f_0
  - pycodestyle=2.6.0=pyh9f0ad1d_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydocstyle=6.1.1=pyhd8ed1ab_0
  - pyflakes=2.2.0=pyh9f0ad1d_0
  - pygments=2.11.2=pyhd8ed1ab_0
  - pylint=2.12.2=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pyproj=3.3.0=py310hff658d0_1
  - pyrsistent=0.18.1=py310he2143c4_0
  - pysocks=1.7.1=py310hbe9552e_4
  - pytest=6.2.5=py310hbe9552e_2
  - pytest-cov=3.0.0=pyhd8ed1ab_0
  - pytest-forked=1.4.0=pyhd8ed1ab_0
  - pytest-mock=3.7.0=pyhd8ed1ab_0
  - pytest-rerunfailures=10.2=pyhd8ed1ab_0
  - pytest-socket=0.5.1=pyhd8ed1ab_0
  - pytest-xdist=2.5.0=pyhd8ed1ab_0
  - python=3.10.2=hd16f9c5_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2021.3=pyhd8ed1ab_0
  - pyyaml=6.0=py310he2143c4_3
  - pyzmq=22.3.0=py310h7939bef_1
  - readline=8.1=hedafd6a_0
  - requests=2.27.1=pyhd8ed1ab_0
  - rtree=0.9.7=py310ha3239f5_3
  - scikit-learn=1.0.2=py310h5f111c3_0
  - scipy=1.7.3=py310h6ecf4ae_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=60.5.0=py310hbe9552e_0
  - shapely=1.8.0=py310haffb4dc_5
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.2.0=py310hbe9552e_2
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - soupsieve=2.3.1=pyhd8ed1ab_0
  - sphinx=4.4.0=pyh6c4a22f_1
  - sphinx-autobuild=2021.3.14=pyhd8ed1ab_0
  - sphinx-copybutton=0.4.0=pyhd8ed1ab_0
  - sphinx-inline-tabs=2022.1.2b11=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_1
  - sqlite=3.37.0=h72a2b83_0
  - stack_data=0.1.4=pyhd8ed1ab_0
  - terminado=0.13.1=py310hbe9552e_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - threadpoolctl=3.0.0=pyh8a188c0_0
  - tiledb=2.6.2=hade11cd_0
  - tk=8.6.11=he1e0b03_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.0=pyhd8ed1ab_1
  - tornado=6.1=py310he2143c4_2
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typed-ast=1.5.2=py310he2143c4_0
  - typing_extensions=4.0.1=pyha770c72_0
  - tzcode=2021e=h3422bc3_0
  - tzdata=2021e=he74cb21_0
  - unicodedata2=14.0.0=py310he2143c4_0
  - urllib3=1.26.8=pyhd8ed1ab_1
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.2.3=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - wrapt=1.13.3=py310he2143c4_1
  - xdoctest=0.15.6=pyhd8ed1ab_0
  - xerces-c=3.2.3=hff64b9e_4
  - xyzservices=2022.1.1=pyhd8ed1ab_0
  - xz=5.2.5=h642e427_1
  - yaml=0.2.5=h3422bc3_2
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.7.0=pyhd8ed1ab_0
  - zlib=1.2.11=hee7b306_1013
  - zstd=1.5.2=h861e0a7_0
  - pip:
    - gdal==3.4.1
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/measure
