name: ci
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

env:
  CONDA_ENV: measure

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      - name: Cache conda
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ hashFiles('environment.yaml') }}
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Setup the project
        run: just setup
      - run: echo $CONDA/envs/$CONDA_ENV/bin >> $GITHUB_PATH
      - run: |
          conda info
      - name: Lint markdown files
        run: just lint-md
      - name: Lint Python files
        run: just lint-python
      - name: Ensure notebook outputs are striped
        run: |
          just notebook-strip
          test -z "$(git status --porcelain)" || (git status; git diff; false)

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      - name: Cache conda
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ hashFiles('environment.yaml') }}
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Setup the project
        run: just setup
      - run: echo $CONDA/envs/$CONDA_ENV/bin >> $GITHUB_PATH
      - name: Run the unit tests
        run: just test
